theme: jekyll-theme-minimal

title: [Portfolio_Rodrigo]
description: [Portfólio de data science. Contatos]

Me pergunto o quanto eu posso escrever aqui e quantos caracteres esse template aceita.
Estou revoltado pelo fato de ser exatamente o template que eu quero, mas não tem espaço para eu adicionar contatos. 
Espero que esse roubo que eu estou fazendo dê certo. 
Beijinhos, beijinhos, tchau tchau baixinhos.

# --- List of links in the navigation bar --- #

navbar-links:
  Contatos:
    - Email: "maltaufrj@gmail.com"
    - Github: "https://github.com/rodrigom-esteves"
    - Twitter: "https://twitter.com/rodrigoma1ta"
    - Kaggle: https://www.kaggle.com/rmesteves

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"
